const types = {

    // auth
    VX_SIGN_IN: 'VX_SIGN_IN',
    VX_CONTINUE_TOKEN: 'VX_CONTINUE_TOKEN',
    VX_GET_MENU: 'VX_GET_MENU',
    VX_SIGN_OUT: 'VX_SIGN_OUT',

    // app
    VX_SIDERBAR_TOGGLE: 'VX_SIDERBAR_TOGGLE',
    VX_ADD_VISITED_VIEW: 'VX_ADD_VISITED_VIEW',
    VX_DEL_VISITED_VIEW: 'VX_DEL_VISITED_VIEW',

    // user
    ST_USER_SIGN_IN: 'ST_USER_SIGN_IN',
    ST_USER_VERIFY_TOKEN: 'ST_USER_VERIFY_TOKEN',

    // calculate
    ST_CALC_IN_STORE: 'ST_CALC_IN_STORE'
}

export default types;